version: '3'
services:
  frontend:
    image: eligundry/fun-messenger-frontend:dev
    container_name: fm-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend-dev
    volumes:
      - .:/opt/fun-messenger-frontend
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/fontend.conf:/etc/nginx/sites-enabled/default

  backend:
    image: eligundry/fun-messenger-backend:dev
    container_name: fm-backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend-dev
    volumes:
      - .:/opt/fun_messenger

  nginx:
    image: nginx:stable
    container_name: fm-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres
    container_name: fm-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/postgres:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine
    container_name: fm-redis

volumes:
  pgdata: {}
