FROM python:3-slim

# Install Python dependencies
ADD ./Pipfile /opt/fun_messenger/Pipfile
ADD ./Pipfile.lock /opt/fun_messenger/Pipfile.lock
WORKDIR /opt/fun_messenger
RUN pip install pipenv
RUN pipenv install --system --deploy

ADD . /opt/fun_messenger
RUN python3 -m compileall fun_messenger

EXPOSE 8000
ENTRYPOINT "/opt/fun_messenger/bin/gunicorn.sh"
